version: '3.8'

services:
  newsfetching:
    build:
      context: ./info-pulse-api/news-fetching-service
      dockerfile: Dockerfile
    ports:
      - "4041:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  newsprocessing:
    build:
      context: ./info-pulse-api/news-processing-service
      dockerfile: Dockerfile
    ports:
      - "4042:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
    restart: unless-stopped